---
- name: Setting up environment
  hosts: localhost
  tasks:
  - name: create dir
    file:
      path: /home/{{ user | default('yahsieh') }}/.vim/autoload/
      state: directory

  - name: get vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/{{ user | default('yahsieh') }}/.vim/autoload/plug.vim
      mode: 0644

  - name: get vimrc
    get_url:
      url: https://raw.githubusercontent.com/yahsieh/workenv/master/.vimrc
      dest: /home/{{ user | default('yahsieh') }}/.vimrc
      mode: 0644

  - name: vim plugin install
    command:
    args:
      cmd: vim -Es -u /home/{{ user | default('yahsieh') }}/.vimrc -c PlugInstall -c qall
      creates: /home/{{ user | default('yahsieh') }}/.vim/plugged/
    become: yes
    become_user: "{{ user | default('yahsieh') }}"

  - name: get gitconfig
    get_url:
      url: https://raw.githubusercontent.com/yahsieh/workenv/master/.gitconfig
      dest: /home/{{ user | default('yahsieh') }}/.gitconfig
      mode: 0644

  - name: get tmux configs
    get_url:
      url: https://raw.githubusercontent.com/yahsieh/workenv/master/{{ item }}
      dest: /home/{{ user | default('yahsieh') }}/
      mode: 0644
    with_items:
    - .tmux.conf
    - .tmux.conf.local
